<?php

/**
 * [BEGIN_COT_EXT]
 * Hooks=tools
 * [END_COT_EXT]
 */
/**
 * plugin Structure Editor for Cotonti Siena
 * 
 * @package structureeditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('plugin', 'plug');
require_once cot_langfile('structureeditor', 'plug');
require_once cot_incfile('structureeditor', 'plug');


$n = 'page';

global $db, $db_structure, $cfg, $cot_extrafields, $structure;

$sql = $db->query("SELECT * FROM $db_structure structure_area = '".$n."' ORDER BY structure_path ASC");

$path = array(); // code path tree
$tpath = array(); // title path tree

foreach ($sql->fetchAll() as $row)
{
	$last_dot = mb_strrpos($row['structure_path'], '.');

	if ($last_dot > 0)
	{
		$path1 = mb_substr($row['structure_path'], 0, $last_dot);
		$path[$row['structure_path']] = $path[$path1].'.'.$row['structure_code'];
		$separaror = ($cfg['separator'] == strip_tags($cfg['separator'])) ? ' '.$cfg['separator'].' ' : ' \ ';
		$tpath[$row['structure_path']] = $tpath[$path1].$separaror.$row['structure_title'];
	}
	else
	{
		$path[$row['structure_path']] = $row['structure_code'];
		$tpath[$row['structure_path']] = $row['structure_title'];
	}

	$struct[$row['structure_code']] = array(
		'path' => $path[$row['structure_path']],
		'tpath' => $tpath[$row['structure_path']],
		'rpath' => $row['structure_path'],
		'id' => $row['structure_id'],
		'tpl' => $row['structure_tpl'],
		'title' => $row['structure_title'],
		'desc' => $row['structure_desc'],
		'icon' => $row['structure_icon'],
	);
}
?>