<?php

/** 
 * [BEGIN_COT_EXT]
 * Hooks=ajax
 * [END_COT_EXT]
 */
 
/**
 * plugin Structure Editor for Cotonti Siena
 * 
 * @package structureeditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

require_once cot_langfile('plugin', 'plug');
require_once cot_langfile('structureeditor', 'plug');
require_once cot_incfile('structureeditor', 'plug');


?>