<?php


/**
 * [BEGIN_COT_EXT]
 * Code=structureeditor
 * Name=Structure Editor
 * Category=misc-ext
 * Description=Easy edit your cats
 * Version=1.0.0
 * Date=2013-08-20
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 *  */

/**
 * plugin Structure Editor for Cotonti Siena
 * 
 * @package structureeditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>