<?php

/**
 * plugin Structure Editor for Cotonti Siena
 * 
 * @package structureeditor
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

?>